"""empty message

Revision ID: c49807776a3e
Revises: d83309123673
Create Date: 2023-10-02 18:37:10.519529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49807776a3e'
down_revision = 'd83309123673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=False))
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('full_name')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
